apiVersion: v1
kind: ReplicationController
metadata:
 name: myapp-rc
 labels:
     app: my-rc-app
spec:
 template:
   metadata:
    name: rep-cont-poda
    labels:
        app: myapp
   spec:
      containers:
       - name: nginx
         image: nginx
 replicas: 2
